import type { Dispatch, SetStateAction } from 'react';
import type { PortalPestana } from '../../components/portal/types';
import type { Materia, Nota, Parcial, Tarea } from '../../core/cursada';
import type { MateriaCondicionesEdicion, ProgresoPlanEdicion } from '../tablero-estado/types';

export interface UseTableroAccionesOptions {
  cargarBD: (mostrarCarga?: boolean) => Promise<boolean>;
  usuarioActual: string | null;
  esAdmin: boolean;
  materias: Materia[];
  inscripciones: { alumno: string; materiaId: string }[];
  parciales: Parcial[];
  notas: Nota[];
  notasInputs: Record<string, string>;
  notasTareasInputs: Record<string, string>;
  materiasExpandidas: Record<string, boolean>;
  materiasDesplegadas: Record<string, boolean>;
  setPestana: Dispatch<SetStateAction<PortalPestana>>;
  setMateriasExpandidas: Dispatch<SetStateAction<Record<string, boolean>>>;
  setMateriasDesplegadas: Dispatch<SetStateAction<Record<string, boolean>>>;
  setAlumnosDesplegados: Dispatch<SetStateAction<Record<string, boolean>>>;
  setNotasDesplegadas: Dispatch<SetStateAction<Record<string, boolean>>>;
  setNotasInputs: Dispatch<SetStateAction<Record<string, string>>>;
  setNotasTareasInputs: Dispatch<SetStateAction<Record<string, string>>>;
  setTareaFoco: Dispatch<SetStateAction<{ materiaId: string; tareaId: string } | null>>;
  setTareaFocoVisible: Dispatch<SetStateAction<boolean>>;
  setProgresoPlanEnEdicion: Dispatch<SetStateAction<ProgresoPlanEdicion>>;
  nuevoAlumnoNombre: string;
  setNuevoAlumnoNombre: Dispatch<SetStateAction<string>>;
  alumnoEnEdicion: { antiguoNombre: string; nuevoNombre: string } | null;
  setAlumnoEnEdicion: Dispatch<SetStateAction<{ antiguoNombre: string; nuevoNombre: string } | null>>;
  nuevaMateriaNombre: string;
  setNuevaMateriaNombre: Dispatch<SetStateAction<string>>;
  nuevoMateriaAnio: string;
  nuevoMateriaCuatrimestre: string;
  materiaCondicionesEnEdicion: MateriaCondicionesEdicion | null;
  setMateriaCondicionesEnEdicion: Dispatch<SetStateAction<MateriaCondicionesEdicion | null>>;
  materiaEnEdicion: { id: string; nombre: string } | null;
  setMateriaEnEdicion: Dispatch<SetStateAction<{ id: string; nombre: string } | null>>;
  nombreTarea: string;
  materiaSel: string;
  fechaInicio: string;
  fechaFin: string;
  detallesTarea: string;
  unidadTarea: string;
  tareaConNota: boolean;
  modoEntregaTarea: import('../../core/cursada').ModoEntregaTarea;
  cupoMaximo: number;
  tipoTarea: string;
  setNombreTarea: Dispatch<SetStateAction<string>>;
  setFechaInicio: Dispatch<SetStateAction<string>>;
  setFechaFin: Dispatch<SetStateAction<string>>;
  setDetallesTarea: Dispatch<SetStateAction<string>>;
  setUnidadTarea: Dispatch<SetStateAction<string>>;
  setTareaConNota: Dispatch<SetStateAction<boolean>>;
  setModoEntregaTarea: Dispatch<SetStateAction<import('../../core/cursada').ModoEntregaTarea>>;
  setCupoMaximo: Dispatch<SetStateAction<number>>;
  setTipoTarea: Dispatch<SetStateAction<string>>;
  tareaEnEdicion: { materiaId: string; tarea: Tarea } | null;
  setTareaEnEdicion: Dispatch<SetStateAction<{ materiaId: string; tarea: Tarea } | null>>;
  materiaHorarioSel: string;
  diaHorario: string;
  horaInicioHorario: string;
  horaFinHorario: string;
  aulaHorario: string;
  setHoraInicioHorario: Dispatch<SetStateAction<string>>;
  setHoraFinHorario: Dispatch<SetStateAction<string>>;
  setAulaHorario: Dispatch<SetStateAction<string>>;
  materiaParcialSel: string;
  nombreParcial: string;
  fechaParcial: string;
  detallesParcial: string;
  parcialEnEdicion: Parcial | null;
  setNombreParcial: Dispatch<SetStateAction<string>>;
  setFechaParcial: Dispatch<SetStateAction<string>>;
  setDetallesParcial: Dispatch<SetStateAction<string>>;
  setParcialEnEdicion: Dispatch<SetStateAction<Parcial | null>>;
  setMateriaParcialSel: Dispatch<SetStateAction<string>>;
}
